---

- name: Install Docker
  block:
    - name: Init universe
      apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present

    - name: Add packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: yes
        cache_valid_time: 86400

    - name: Add key in Docker
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      register: "add_repository_key"  

    - name: Install stable repo
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        filename: docker

    - name: Install docker-ce
      apt:
        name: "docker-ce"
        update-cache: yes

    - name: Check Docker instaled
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Install docker-compose
      apt:
        name: "docker-compose-plugin"
        update-cache: yes

    - name: Check Docker instaled
      service:
        name: docker
        state: restarted
        enabled: yes    
  become: yes
  
- name: Set python packages
  block:
    - name: Install pip packages
      pip:
        name: docker
      register: page

- name: Continue install
  block:
    - name: Add in Docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

