---
- name: Preconfig
  tasks:
    - name: Install Postgres
      block:

        - name: Add key in Postgres
          apt_key:
            url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
            state: present

        - name: Install stable repo
          apt_repository:
            repo: >
              "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main"
            state: present
            update-cache: yes
            filename: postgres

        - name: Install postgres
          apt:
            name: postgresql
            update-cache: yes

        - name: Check Postgres instaled
          service:
            name: postgresql
            state: restarted
            enabled: yes
      become: yes

    - name: Continue install
      block:
        - name: Добавление пользователя в группу Postgres
          user:
            name: "{{ ansible_user }}"
            group: postgres
            append: yes

