---
- name: Install Postgres
  block:
    - name: "Install packages"
      dnf: 
        name: postgresql-server 
        state: present

    - name: "Install packages"
      dnf: 
        name: postgresql 
        state: present

    - name: "Install Python packages"
      pip: 
        name: psycopg2-binary
        state: present

    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service: 
        name: postgresql
        state: started 
        enabled: yes
  become: yes      
