- name: create neonevm group
  group:
    name: neonevm
    system: true
    state: present

- name: create neonevm system user
  user:
    name: "{{ neonevm_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: neonevm
    home: /home/{{ neonevm_user }}/

- name: ensure neonevm has access to run docker
  user:
    name: "{{ neonevm_user }}"
    groups: docker
    append: yes

- name: create config dir 
  file:
    path: "{{ neonevm_config_dir }}"
    owner: root
    group: neonevm 
    mode: 0770 
    state: directory
    
- name: create neon evm solana keypair if not already present
  command: /root/.local/share/solana/install/releases/"{{ solana_version }}"/solana-release/bin/solana-keygen new -o "{{ neonevm_solana_keypair }}" --no-bip39-passphrase -s
  become: true
  become_user: root
  args:
    chdir: "{{ neonevm_config_dir }}"
    creates: "{{ neonevm_solana_keypair }}"

- name: ensure permissions on neonevm keypair
  file:
    path: "{{ neonevm_solana_keypair }}"
    owner: "{{ neonevm_user }}"
    group: neonevm
    mode: 0600

- name: check neon evm pubkey
  command: /root/.local/share/solana/install/releases/"{{ solana_version }}"/solana-release/bin/solana-keygen pubkey 
  register: res_pubkey

- name: save public key hash
  set_fact:
    neonevm_public_key_hash: "{{ res_pubkey.stdout }}"

- debug: msg="Neon EVM Solana public key hash {{ neonevm_public_key_hash }}"

- name: write solana public key to file
  local_action: |
    copy dest=neonevm.pub content="{{ neonevm_public_key_hash }}" 
  become: false


