--- 

  - name: deploy postgres docker container
    docker_container:
      image: postgres:14.0
      name: postgres
      state: started
      detach: yes
      auto_remove: false
      env: 
        PGPORT: 5433
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_DB: "{{ postgres_db }}"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        SOLANA_URL: "{{ neonevm_solana_rpc }}"
      ports:
        - "8080:80"

# - name: Create the database specified in vars
#   become: true
#   become_user: postgres
#   postgresql_db: 
#     name: "{{ postgres_db }}"
#     template: "template0"
#     state: present

# - name: User fot
#   become: true
#   become_user: postgres
#   postgresql_user: 
#     db: "{{ postgres_db }}"
#     name: "{{ postgres_user }}"
#     password: "{{ postgres_password }}"
#     priv: ALL
#     state: present

# - name: Ensure user does not have unnecessary permissions
#   become: true
#   become_user: postgres
#   postgresql_user: 
#     name: "{{ postgres_user }}"
#     role_attr_flags: NOSUPERUSER,NOCREATEDB
#     state: present