---

  - name: deploy neonEVM docker container
    docker_container:
      image: neonlabsorg/proxy:stable
      name: neonEVM
      state: started
      detach: yes
      auto_remove: false
      env: 
        CONFIG: devnet
        POSTGRES_DB: "{{ postgres_db }}"
        POSTGRES_USER: "{{ postgres_user }}"
        POSTGRES_PASSWORD: "{{ postgres_password }}"
        SOLANA_URL: "{{ neonevm_solana_rpc }}"
      ports:
        - "8080:80"