- name: deploy rpc hosts
  remote_user: root
  hosts: 
    - 127.0.0.1
  vars:
    neonevm_enabled: true
    neonevm_env:
      POSTGRES_HOST: 127.0.0.1
    

  roles:
    - configure_ubuntu
    - solana_cli
    - bootstrap
    - postgres
    - neon_install
#    - monitoring



