#neon_config
neonevm_user: "neon-proxy"
neonevm_version: "latest"
neonevm_solana_rpc: "localhost"

neonevm_default_envs:
  devnet:
    CONFIG: devnet
    SOLANA_URL: "{{ neonevm_solana_rpc }}"
neonevm_chains: 
  testnet: "0xe9ac0dc"
  devnet: "0xe9ac0ce"
  mainnet: "0xe9ac0d6"

#neonevm  
neonevm_env: "{{ neonevm_default_envs[neonevm_network] }}"
neonevm_config_dir: /etc/neonevm/
neonevm_solana_keypair: "{{ neonevm_config_dir }}neonevm-keypair.json"

#postgres
postgres_db: "neon-db"
postgres_user: "{{ neonevm_user }}"
postgres_password: neon-proxy-pass

#solana_config
solana_version: "v1.11.6"
solana_rpc_port: 8899
open_solana_ports_start: 8000
open_solana_ports_end: 10000
solana_home: "/home/solana"
